### ISSUE TITLE
Awesome shell prompt!

### ISSUE THREAD

**Issue by gazsp** [diegoulloao/neofusion.kitty#1]
Can you please tell me how to get the awesome shell prompt you're using in the screenshots? Is this ZSH?

Awesome theme by the way :-) 

Cheers,
Gaz.

**Comment by gazsp** [comment]
Don't worry, sussed it. Powerlevel10k rocks :D

**Comment by diegoulloao** [comment]
Glad you like it! Yes, using p10k ✨
BTW, I added a tabs customization instructions in the readme (update)

**Comment by gazsp** [comment]
Love it - thanks!
